version: '3'
services:
  app:
    container_name: ioc_app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    container_name: ioc_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
